CHAPTER1 = [
	label, "START01",
	
	//Begin First Scene
	label, "Scene_1",
	
	scene, {src:"black"},
	box, {pos:"center", back:"none"},
	macro, "change_to_Title",
	box, {show:false},
	macro, "change_to_Dialogue",
	scene, {src:"Background Images/Final/study_color_lineless01.jpg", effect:"dissolve"},
	box, {pos: "bottom", back:"image"},
	text, {align:"left", duration:0.1},
	
	//_skip_text is a predefined variable in the engine that skips through the text
	//For debuggin purposes, we can set this to true/false to get to where we need.
	
	set, {_skip_text:false},
	set, {suspect1:false, suspect2:false, suspect3:false, suspect4:false},
	set, {clue2:false, clue3:false, clue4:false},
	set, {correctitem1:true, correctitem2:false, correctitem3:false, correctitem4:false},
	set, {activescene1:true},
	set, {maidGlass:false},
	set, {interrogationmode:true, suspectmode:false},
	text, {value:"*\nLocation: Detective's Study"},
	actor, {id:"Detective_Main", nick:"?????", sprite:["MC", "Character Sprites/Final/DetectiveNeutralHatResize.png", "FLOOR"], position: "center", effect:"none" },
	actor, {id:"Detective_Main", say:"I told you, I'm not interested."},
	text, {speaker:"Courier", value:"But...ma'am..."},
	actor, {id:"Detective_Main", say:"And I told you not to call me 'ma'am'."},
	text, {speaker:"Courier", value:"Miss, please, if you read the letter, it says that--"},
	actor, {id:"Detective_Main", say:"I read the first letter he sent me. Why does he think that sending me another one is going to change my mind? I told him, its a waste of time."},
	actor, {id:"Detective_Main", say:"Why he expects me to travel halfway across the county just to point out the obvious to him, I don't know, but he already has his answer."},
	actor, {id:"Detective_Main", say:"I."},
	actor, {id:"Detective_Main", say:"Won't.", append:true},
	actor, {id:"Detective_Main", say:"Do.", append:true},
	actor, {id:"Detective_Main", say:"It.", append:true},
	text, {speaker:"Courier",  value:"But, miss--"},
	actor, {id:"Detective_Main", say:"Detective."},
	text, {speaker:"Courier", value:"Pardon me?"},
	actor, {id:"Detective_Main", nick:"Hawkshaw", say:"My name is Detective Hawkshaw, not 'miss'."},
	text, {speaker:"Courier", value:"Er...yes. Miss Detective Hawkshaw--"},
	actor, {id:"Detective_Main", say:"*sigh*"},
	text, {speaker:"Courier", value:"--if you would read the second letter, you'd notice that he's amended his offer."},
	actor, {id:"Detective_Main", say:"...has he now?"},
	text, {speaker:"Courier", value:"He understands the great expense of travel and lodging you'd be undertaking, and he wants you to know that you need not concern yourself with it."},
	text, {speaker:"Courier", value:"All of your expenses will be paid for in full. In addition, he's more than doubled the amount he'll compensate you for. Please, if you were to just read..."},
	actor, {id:"Detective_Main", say:"...More than doubled?"},
	text, {speaker:"Courier", value:"Yes, ma'am."},
	actor, {id:"Detective_Main", say:"....Let me see that letter."},
	text, {speaker:" ", value:"You have received the Mayor's Letter!"},
	set, {clue1:true},
	actor, {id:"Detective_Main", say:"..."},
	actor, {id:"Detective_Main", say:"...", append:true},
	actor, {id:"Detective_Main", say:"...", append:true},
	actor, {id:"Detective_Main", say:"...I see, more than doubled.", append:true},
	text, {speaker:"Courier", value:"Yes, ma'am. And all expenses paid for--"},
	actor, {id:"Detective_Main", say:"I heard you the first time. Hmm...how far is this...'Clandes Town', again?"},
	text, {speaker:"Courier", value:"Two days by carriage, ma'am. Everything's already been arranged for you. All you have to do is agree."},
	actor, {id:"Detective_Main", say:"...*sighs* Very well then. You can tell the Mayor that I'll see him two days hence. Be sure to tell him I fully expect him to provide me with adequate lodgings, and not some shoddy old tavern room to keep me quiet."},
	actor, {id:"Detective_Main", say:"And more than double to compensate me, after travel and lodging expenses. Is that clear?"},
	text, {speaker:"Courier", value:"Yes, ma'am."},
	actor, {id:"Detective_Main", say:"Oh, and one other thing--if the Mayor is so intent on hiring me, he should also know that I do not work with local law enforcement."},
	actor, {id:"Detective_Main", say:"They are not to interfere with my investigation, and I do not want their input, considering they've obviously failed already at their job. Is that clear?"},
	text, {speaker:"Courier", value:"It is, ma'am."},
	actor, {id:"Detective_Main", say:"Tell your people I'll be ready to leave this evening. I won't need help packing, but I'll need help carrying it all."},
	text, {speaker:"Courier", value:"Of course, ma'am."},
	actor, {id:"Detective_Main", say:"And sir?"},
	text, {speaker:"Courier", value:"Yes, ma'am?"},
	actor, {id:"Detective_Main", say:"I told you not to call me ma'am."},
	text, {speaker:"Courier", value:"Of course, ah...Detective Hawkshaw."},
	//End First Scene
	actor, {id:"Detective_Main", remove:"actor"},
	box, {show: false},
	//button, {name:"skipshit", x:400, y:300, base:"rgba(225,0,100,0.25)", hover:"rgba(227,221,204,0.5)"},},
	
	//Scene Transition
	scene, {src:"black", effect:"dissolve"},
	box, {pos:"center", back:"none"},
	macro, "change_to_Title",
	text, {align:"center", value:"Two days later", effect:"fade", duration:3},
	box, {show:false},
	macro, "change_to_Dialogue",
	
	//2nd Scene
	label, "Scene_2",
	scene, {src:"Background Images/Final/town_color01.jpg", effect: "dissolve"},
	audio, {bgm:"Music/town", format:["ogg"]},
	box, {pos:"bottom", back: "image"},
	text, {align:"left", duration:0.1},
	
	//set, {_skip_text:false},
	text, {value:"\nLocation: Clandes Town"},
	macro, "change_to_Thought",
	actor, {id:"Detective_Main", nick:"Hawkshaw", color:"#f5f5f5", sprite:["MC", "Character Sprites/Final/DetectiveNeutralHatResize.png", "FLOOR"], position: "left"},
	actor, {id:"Detective_Main", show:false},
	actor, {id:"Detective_Main", say:"(...Clandes Town...population, only a few hundred...)"},
	actor, {id:"Detective_Main", say:"(God, I hope double the payment is worth staying in this little thorp of a town. At least it won't take long to tell the Mayor what he already knows...)"},
	macro, "change_to_Dialogue",
	text, {speaker:"C.Driver", value:"We've arrived, ma'am."},
	actor, {id:"Detective_Main", say:"Have we?"},
	actor, {id:"Detective_Main", say:"Very well then..."},
	text, {speaker:"Hawkshaw", value:"..."},
	text, {speaker:"Hawkshaw", value:"...Oh, I do hate getting in and out of carriages..."},
	actor, {id:"Detective_Main", show:true},
	actor, {id:"Detective_Main", say:"Bring my luggage to wherever the Mayor is having me stay."},
	actor, {id:"Detective_Main", say:"I'm suppose to be meeting the Constable here. I believe 'Aldwin Bungle' was his name."},
	text, {speaker:"C.Driver", value:"Very good, ma'am."},
	actor, {id:"Detective_Main", say:"...*sigh*"},
	macro, "change_to_Thought",
	actor, {id:"Detective_Main", say:"(Oh, wonderful. He said that he'd be here around this time...ah, there he is.)"},
	macro, "change_to_Dialogue",
	actor, {id:"Detective_Main", say:"Sir?"},
	actor, {id:"Constable", nick:"Aldwin B.", color:"#f5f5f5", sprite:["C_Main", "Character Sprites/Final/ConstableNeutralResize.png", "FLOOR"], position: "right"},
	actor, {id:"Constable", say:"..."},
	//actor, {id:"Detective_Main", sprite:["MC_2", "Character Sprites/Final/DetectiveNeutralResize.png", "FLOOR"], position: "left"},
	actor, {id:"Detective_Main", say:"...Sir?"},
	actor, {id:"Constable", say:"Huh? Oh...good day, ma'am."},
	actor, {id:"Detective_Main", say:"Are you the Constable?"},
	actor, {id:"Constable", say:"Yes. Is there, ah, something you needed, ma'am?"},
	actor, {id:"Detective_Main", say:"I was told to talk to you."},
	actor, {id:"Constable", say:"Oh, if you have some business you need us to attend to, you can visit me at the Police Station, perhaps in a few hours? I'm...otherwise engaged at the moment..."},
	actor, {id:"Detective_Main", say:"...I was told you would meet with me."},
	actor, {id:"Constable", say:"Oh, were you? I'm sorry. Whoever told you that must've been mistaken. I'm currently waiting for a 'Detective Hawkshaw'."},
	actor, {id:"Detective_Main", say:"I am 'Detective Hawkshaw'."},
	actor, {id:"Constable", say:"...His wife?"},
	actor, {id:"Detective_Main", sprite:["MC_2", "Character Sprites/Final/DetectiveNeutralResize.png", "FLOOR"], position: "left"},
	actor, {id:"Detective_Main", say:"No. I am Detective Hawkshaw."},
	macro, "change_to_Thought",
	
	text, {value: "\n(It seems that I will have to show him something in order for him to believe me.  I should have the means to do so in my journal.)"},
	actor, {id:"Detective_Main", show:false},
	actor, {id:"Constable", show:false},
	box, {show: false},
	
	label, "Town",
	cform, ["interface", true,
	button, {name: "PopJournal", x:35, y: 0, w: 75, h: 76, base:"Images/journal_icon.png",
		link:[jump, "First_Time_Inventory"], showText: false},
	],
	jump, "Town",
	
	label, "First_Time_Inventory",
	cform, "close",
	jump, "journal#journalShow",
	
	label, "InventoryOpen",
	cform, "close",
	jump, "journal#journalon",
	
	label, "Letter_Clicked",
	box, {pos:"bottom", back:"image"},
	actor, {id:"Constable", show:true},
	macro, "change_to_Dialogue",
	actor, {id:"Constable", say:"You...? Oh, Pardon me, ma'am, I didn't think..."},
	actor, {id:"Detective_Main", show:true},
	actor, {id:"Detective_Main", say:"Please, don't call me ma'am."},
	actor, {id:"Constable", say:"Then, what should I call you?"},
	actor, {id:"Detective_Main", say:"Detective."},
	actor, {id:"Constable", say:"Of course."},
	actor, {id:"Detective_Main", say:"Where is everyone? Or is this town even more empty than I was led to believe?"},
	actor, {id:"Constable", say:"It's Sunday, ma--- Excuse me, Detective."},
	actor, {id:"Detective_Main", say:"And?"},
	actor, {id:"Constable", say:"...Everyone's in Church."},
	actor, {id:"Detective_Main", say:"Oh, right. I suppose most people do visit church on Sundays..."},
	actor, {id:"Constable", say:"Er...yes. Anyways, Detective, allow me to show you to my father's estate, and--"},
	actor, {id:"Detective_Main", say:"Your father's?"},
	actor, {id:"Constable", say:"I mean...the Mayor's! The Mayor's estate."},
	actor, {id:"Detective_Main", say:"The Mayor is your father?"},
	actor, {id:"Constable", say:"Yes, he is. Anyway, let me show you the way to the estate and to the, uh...crime scene."},
	actor, {id:"Detective_Main", say:"It's still a crime scene, after all this time?"},
	actor, {id:"Constable", say:"My father--I mean, the Mayor--has asked that the place be left untouched for your arrival, Detective."},
	actor, {id:"Detective_Main", say:"Hmm. How thoughtful. Very well then, show me the way."},
	box, {show: false},
	actor, {id:"Detective_Main", remove:"actor"},
	actor, {id:"Constable", remove:"actor"},
	
	//scene transition
	/*
	scene, {src:"black", effect:"dissolve"},
	box, {pos:"center", back:"none"},
	macro, "change_boxFontStyle_2",
	text, {align:"center", value:"At the Mayor's Manor", effect:"fade", duration:0},
	box, {show:false},
	macro, "change_boxFontStyle_1",
	
	*/
	scene, {src:"Background Images/Final/foyer_color01.jpg", effect: "none"},
	audio, {bgm:"Music/foyer", format:["ogg"]},

	box, {pos:"bottom", back:"image"},
	
	text, {align:"left", duration:0.1},
	text, {value:"\nLocation: Manor Foyer"},
	actor, {id:"Detective_Main", nick:"Hawkshaw", color: "#f5f5f5", sprite:["MC", "Character Sprites/Final/DetectiveNeutralResize.png", "FLOOR"], position: "left"},
	actor, {id:"Constable", nick:"Aldwin B.", color: "#f5f5f5", sprite:["C_Main", "Character Sprites/Final/ConstableNeutralResize.png", "FLOOR"], position: "right"},
	actor, {id:"Constable", say:"So...I'm sure my father had explained to you the situation..."},
	actor, {id:"Detective_Main", say:"He's told me that his wife, after her daily walk in her garden, collapsed at the dining table and died soon afterward, and that local law enforcement..."},
	actor, {id:"Detective_Main", say:"...has run out of leads and has pronounced her death as an accidental poisoning from one of the plants in her garden."},
	actor, {id:"Constable", say:"Yes, exactly...he was hoping that you could--"},
	actor, {id:"Detective_Main", say:"He is aware that they found poisonous plants in her garden, yes?"},
	actor, {id:"Constable", say:"He...yes, but--"},
	actor, {id:"Detective_Main", say:"But he still believes his wife's death was not accidental?"},
	actor, {id:"Constable", say:"Look...she wouldn't have made a mistake like that. If there was one thing she was knowledgeable about, it was her plants. She loved that garden."},
	actor, {id:"Constable", say:"God, if you asked, she'd sit there and recite every scientific name of every plant she kept. She wouldn't have mistaken a poisonous plant for one that wasn't."},
	actor, {id:"Detective_Main", say:"Your colleagues seem to think that's exactly what she did."},
	actor, {id:"Constable", say:"They...didn't know her."},
	actor, {id:"Detective_Main", say:"You know, it's not very customary for relatives of the victim to conduct the investigation..."},
	actor, {id:"Constable", say:"...I don't see how that's your business, ma'am."},
	actor, {id:"Detective_Main", say:"Detective."},
	actor, {id:"Constable", say:"Yes, Detective. I don't see how that's--"},
	actor, {id:"Detective_Main", say:"Of course it's my business. Your father brought me here to investigate the death of his wife. How the previous investigation was conducted is very relevant, ..."},
	actor, {id:"Detective_Main", say:"...considering that if, on the off chance he is right, that means you and your office failed to see it."},
	actor, {id:"Constable", say:"...I see..."},
	actor, {id:"Detective_Main", say:"Good. Then we're in agreement."},
	
	//End of Scene 2
	actor, {id:"Detective_Main", remove:"actor"},
	actor, {id:"Constable", remove:"actor"},
	box, {show:false},
	
	
	label, "Scene_3",
	set, {correctitem1:false},
	set, {activescene1:false},
	set, {activescene2:true},
	set, {interrogationmode:false},
	scene, {src:"Background Images/Final/foyer_color01.jpg", effect: "none"},

	box, {pos:"bottom", back:"image"},
	
	actor, {id:"Detective_Main", nick:"Hawkshaw", color: "#f5f5f5", sprite:["MC", "Character Sprites/Final/DetectiveNeutralResize.png", "FLOOR"], position: "left"},
	actor, {id:"Mayor", nick:"M. Calvin", color: "#f5f5f5", sprite:["M_Main", "Character Sprites/Final/MayorNeutralResize.png", "FLOOR"], position: "right", effect:"none"},
	actor, {id:"Mayor", say:"Good Afternoon, Detective Hawkshaw. I trust your trip went well?"},
	actor, {id:"Detective_Main", say:"It went fine, Sir..."},
	actor, {id:"Mayor", say:"Bungle. Calvin Bungle. Mayor of Clandes Town."},
	actor, {id:"Detective_Main", say:"Yes, Mayor Bungle. The trip went fine."},
	actor, {id:"Mayor", say:"Very good, I expect you're very tired after your journey..."},
	actor, {id:"Detective_Main", say:"Actually, I'm fine. I was told I was to see the crime scene..."},
	actor, {id:"Mayor", say:"Well, you don't waste time, do you? But before we do, would you like some tea?"},
	actor, {id:"Detective_Main", show:false},
	actor, {id:"Constable", nick:"Aldwin B.", color: "#f5f5f5", sprite:["C_Main_2", "Character Sprites/Final/ConstableNeutralResizeFlipped.png", "FLOOR"], position: "left"},
	actor, {id:"Constable", say:"Yes, please--"},
	actor, {id:"Constable", show:false},
	actor, {id:"Detective_Main", show: true},
	actor, {id:"Detective_Main", say:"No thank you, sir. I'm sure you'd like me to have a look at the crime scene as soon as possible."},
	actor, {id:"Mayor", say:"Very well...this way..."},
	actor, {id:"Detective_Main", remove:"actor"},
	actor, {id:"Constable", remove:"actor"},
	actor, {id:"Mayor", remove:"actor"},
	box, {show:false},
	
	//audio, {bgm:"foyer", action:"stop"},
	jump, "Chapter_1_Maps#Tutorial_Inv_Scene",
	
	label, "Scene_3b",
	box, {pos:"bottom", back:"image"},
	text, {value:"\nLocation: Dining Room"},
	actor, {id:"Mayor", nick:"M. Calvin", color: "#f5f5f5", sprite:["M_Main", "Character Sprites/Final/MayorNeutralResize.png", "FLOOR"], position: "right"},
	actor, {id:"Mayor", say	:"I...I really do appreciate you coming all this way, Detective Hawkshaw. I've heard so much about your work in London, and your name is the most esteemed of all detectives in Britain..."},
	actor, {id:"Detective_Main", nick:"Hawkshaw", color: "#f5f5f5", sprite:["MC", "Character Sprites/Final/DetectiveNeutralResize.png", "FLOOR"], position: "left"},
	actor, {id:"Detective_Main", say:"Hm. It seems like this place has been untouched since the crime took place."},
	actor, {id:"Mayor", say:"Y-Yes, I made proper care not to tamper with the crime scene or any possible evidence."},
	actor, {id:"Detective_Main", say:"I see, thank you."},
	actor, {id:"Mayor", say:"I...just hoped that you could look into this. I-I know s-she wouldn't have made such a mistake...someone had to have done this to her..."},
	actor, {id:"Detective_Main", say:"I will discover the truth, Mayor Bungle.  Now, allow me to begin my investigation starting here."},
	actor, {id:"Detective_Main", show:false},
	actor, {id:"Mayor", show:false},
	set, {_skip_text:false},
	
	macro, "change_to_Thought",
	text, {value:"\n(Alright then, let's have a look around.)"},
	box, {show:false},
	
	jump, "Chapter_1_Maps#Inv_Scene_1.1",
	
	label, "Exit_Inv_Scene_1.1",
	set, {Hemlock_clicked:false},
	set, {Dish_clicked:false},
	set, {Table_clicked:false},
	macro, "Moving_Scenes_Off",
	box, {pos:"bottom", back:"image"},
	set, {_skip_text:false},
	actor, {id:"Detective_Main", show:true},
	actor, {id:"Detective_Main", say:"...Constable, what types of poisonous plants were documented in the garden?"},
	actor, {id:"Constable", nick:"Aldwin B.", color: "#f5f5f5", sprite:["C_Main", "Character Sprites/Final/ConstableNeutralResize.png", "FLOOR"], position: "right"},
	actor, {id:"Constable", say:"Oleander was found in the garden, and they...we thought that she might have come into contact with it when pruning the other plants.  If she touched her mouth or food afterward, it might explain how she was poisoned...Why do you ask?"},
	actor, {id:"Detective_Main", say:"I found this plant on the floor, and it isn't Oleander.  Did you or your colleagues encounter any Hemlock in the gardens?"},
	actor, {id:"Constable", say:"Ah...no, ma...excuse me, Detective. There isn't any Hemlock."},
	actor, {id:"Detective_Main", say:"There is, right here."},
	actor, {id:"Constable", show:false},
	actor, {id:"Mayor", nick:"M. Calvin", color: "#f5f5f5", sprite:["M_Main", "Character Sprites/Final/MayorNeutralResize.png", "FLOOR"], position: "right"},
	actor, {id:"Mayor", say:"...W-What?! What does that mean?"},
	actor, {id:"Detective_Main", say:"If the Hemlock wasn't in the garden, then somebody put it here."},
	actor, {id:"Detective_Main", show:false},
	actor, {id:"Constable", sprite:["C_Main_2", "Character Sprites/Final/ConstableNeutralResizeFlipped.png", "FLOOR"], position: "left"},
	actor, {id:"Constable", say:"Good God..."},
	actor, {id:"Mayor", say:"I...I was right, then? She was murdered? She didn't just make a mistake?"},
	actor, {id:"Constable", remove:"C_Main_2", show:false},
	actor, {id:"Detective_Main", show:true, say:"So it would seem. Mayor Bungle, I need to know everyone who was in contact with her the day leading up to the murder, and all of her appointments. Did your wife have any enemies? Anyone who might want to hurt her?"},
	actor, {id:"Mayor", say:"N-No, of course not! Everyone loved her...she was so generous with her time. She devoted her entire life to giving to those less fortunate than her. I can't imagine anyone would ever want to harm her!"},
	actor, {id:"Detective_Main", say:"Well, clearly, someone did. I'll also need to know who her friends were, who she talked to the most--"},
	actor, {id:"Mayor", say:"Everyone was her friend, Detective. She was well loved by the entire town..."},
	actor, {id:"Detective_Main", say:"Surely, she had friends that were closer to her than others though."},
	actor, {id:"Mayor", say:"I...very well. I'll get you a list of people...Oh, Alvin here can also help you with that. He knew all of them, and can show you where they live."},
	actor, {id:"Detective_Main", say:"I thought I made it explicitly clear that I wanted no assistance from local law enforcement."},
	actor, {id:"Mayor", say:"Of course you did, Detective. But how do you expect to find each of these people without help?"},
	actor, {id:"Mayor", remove:"actor"},
	actor, {id:"Detective_Main", say:"It's a small enough town. I'll be fine."},
	actor, {id:"Constable", show:true, sprite:"C_Main", position:"right", say:"With all due respect, Detective...things might move, ah...faster if you allowed me to help you."},
	actor, {id:"Detective_Main", say:"...*sigh*\nFine then, you may help, But you will not interfere with my investigation. If you want me here, the you'll allow me to operate on my own terms, Is that clear?"},
	actor, {id:"Constable", say:"Of course it is, Detective."},
	actor, {id:"Detective_Main", say:"Very good. ...Oh yes, I'll be taking this book with me."},
	actor, {id:"Constable", say:"My mothe--the victim's Appointment Book? ...Very well. I trust you to lead this case. Take what you think you'll need for this investigation."},
	actor, {id:"Detective_Main", say:"Excellent. Let's not waste any time, then."},
	actor, {id:"Detective_Main", remove:"actor"},
	actor, {id:"Constable", remove:"actor"},
	set, {_skip_text:false},
	box, {show:false},

	audio, {bgm:"Music/foyer", format:["ogg"]},	
	scene, {src:"Background Images/Final/foyer_color01.jpg", effect:"dissolve"},
	
	box, {pos:"bottom", back:"image"},
	macro, "change_to_Thought",
	text, {align:"left", speaker:"Hawkshaw", value:"(Hmm...I feel like I should ask some questions to Constable Alvin and Mayor Bungle. Who to start with first?)"},
	macro, "change_to_Dialogue",
	text, {speaker:"Game", value:"You have added Aldwin and Calvin Bungle to the suspect list!"},
	set, {suspect1:true},
	set, {suspect2:true},
	set, {inter_People_Total:0},
	set, {Aldwin_Chapter1_1st:false},
	set, {Calvin_Chapter1_1st:false},
	
	//Andy, Here you implement the menu system as we don't have the World Map or a Local Map in general. Have two options for both the Constable and Mayor, and these will branch off into 
	//the interrogrations. Refer to demos for details.
	label, "interrogationChoice",
	//menu, ["Select a person for interrogation:",
		//"Constable Aldwin Bungle, I'm going to have to ask you a few questions", "Aldwin",
	
	//"Mayor Calvin Bungle", "Calvin" ],
    actor, {id:"Detective_Main", nick:"Hawkshaw", color: "#f5f5f5", sprite:["MC", "Character Sprites/Final/DetectiveNeutralResize.png", "FLOOR"], position: "left", show:false},
	actor, {id:"Constable", nick:"Aldwin B.", color: "#f5f5f5", sprite:["C_Main", "Character Sprites/Final/ConstableNeutralResize.png", "FLOOR"], position: "left", show:false},
	actor, {id:"Mayor", nick:"M. Calvin", color: "#f5f5f5", sprite:["M_Main", "Character Sprites/Final/MayorNeutralResize.png", "FLOOR"], position: "right", show:false},
	label, "interrogationSelect",
	macro, "change_to_Menu",
	menu, ["Select",
		   "Constable Aldwin Bungle", "Aldwin_0",
		   "Mayor Calvin Bungle", "Calvin_0",
		   "I'm done with questioning", "End_Interrogation_0" ],
		   
	label, "Aldwin_0",
	macro, "change_to_Dialogue",
	jump, {Aldwin_Chapter1_1st:true, label:"Aldwin"},
	set, {inter_People_Total:"+1"},
	set, {Aldwin_Chapter1_1st:true},
	jump, "Aldwin",
	
	label, "Aldwin",
	macro, "change_to_Dialogue",
	actor, {id:"Mayor", show:false},
	actor, {id:"Constable", show:false},
	actor, {id:"Detective_Main", show:false},
	actor, {id:"Detective_Main", show:true},
	//actor, {id:"Detective_Main", nick:"Hawkshaw", color: "#f5f5f5", sprite:["MC", "Character Sprites/Final/DetectiveNeutralResize.png", "FLOOR"], position: "left"},
	actor, {id:"Constable", show:true, position: "right"},
	actor, {id:"Detective_Main", say:"A word, if you will, Constable."},
	actor, {id:"Constable", say:"Me? Why?"},
	actor, {id:"Detective_Main", say:"You are related to the woman, are you not?"},
	actor, {id:"Constable", say:"She is.. was... my mother.  So, yes..."},
	label, "AldwinFirstSelection",
	macro, "change_to_Menu",
	menu, ["Select Topic:",
		"Relationship with mother", "relationship",
		"Last time you saw her", "lasttime",
		"I'm done with you", "interrogationSelect"],
	//we might need some variable that checks which option has been used already, will consider after today's presentation

	label, "relationship",
	macro, "change_to_Dialogue",
	actor, {id:"Detective_Main", say:"Mr. Bungle, how would you describe your relationship with the deceased?"},
	actor, {id:"Constable", say:"Can you please just call her by her name? It’s still so weird to think that she’s... gone..."},
	actor, {id:"Detective_Main", say:"She’s dead, and unless you fully cooperate with me I’m going to have to assume that you’re hiding something."},
	actor, {id:"Constable", say:"W-what?! No I’m not! Just... *sigh* ...could you try to be a little more sensitive about what everyone is going through?"},
	actor, {id:"Detective_Main", say:"Sensitivity is for civilians, Mr. Bungle. Now, how would you characterize your relationship with...Rachel Lind."},
	actor, {id:"Constable", say:"My mother always cared for me in my youth. She was a kind, generous soul, and seemed to want nothing but the best for everyone in town."},
	macro, "change_to_Thought",
	actor, {id:"Detective_Main", say:"(He hasn’t told me anything about how he feels about her now... This is suspicious.)"},
	macro, "change_to_Dialogue",
	actor, {id:"Detective_Main", say:"You didn’t tell me exactly how you feel about her, Mr. Bungle."},
	actor, {id:"Constable", say:"Didn’t I? I said she cared for me..."},
	actor, {id:"Detective_Main", say:"In your youth. Not now."},
	actor, {id:"Constable", say:"She still cares for me."},
	macro, "change_to_Menu",
	menu, ["Select",
		"Back to the first set of questions", "AldwinFirstSelection",
		"Accuse Aldwin of being a liar", "AldwinLiar"],
	label, "AldwinLiar",
	macro, "change_to_Dialogue",
	actor, {id:"Detective_Main", say:"You’re hiding something from me, Mr. Bungle."},
	actor, {id:"Constable", say:"What!? Where did you get that idea?"},
	actor, {id:"Detective_Main", say:"Mr. Bungle, answer the question honestly."},
	actor, {id:"Constable", say:"...*Sigh* My mother and I have been... distant lately. I hadn’t seen her as much as I should have, but... I don’t know what’s gotten into her.  It just gets tense when I talk about cases.  Maybe you should ask my father, he’ll have better insight."},
	text, {align:"left", speaker:"Journal", value:"A new clue has been added!"},
	jump, "AldwinFirstSelection",
	
	label, "lasttime",
	macro, "change_to_Dialogue",
	actor, {id:"Detective_Main", say:"When did you last see Rachel Lind?"},
	actor, {id:"Constable", say:"Uhm... a few days ago. I had dinner with her and my father."},
	actor, {id:"Detective_Main", say:"How did she seem then?"},
	actor, {id:"Constable", say:"Fine."},
	macro, "change_to_Thought",
	actor, {id:"Detective_Main", say:"(...Well, that’s a rather short answer...)"},
	macro, "change_to_Menu",
	menu, ["Select",
		"Back to other questions", "AldwinFirstSelection",
		"Press for more info", "AldwinPressContinue"],
	label, "AldwinPressContinue",
	macro, "change_to_Dialogue",
	actor, {id:"Detective_Main", say:"Could you elaborate?"},
	actor, {id:"Constable", say:"She just seemed fine. Normal."},
	macro, "change_to_Thought",
	actor, {id:"Detective_Main", say:"(Maybe I should ask him something else.)"},
	macro, "change_to_Dialogue",
	jump, "AldwinFirstSelection",
		
	label, "Calvin_0",
	macro, "change_to_Dialogue",
	jump, {Calvin_Chapter1_1st:true, label:"Calvin"},
	set, {inter_People_Total:"+1"},
	set, {Calvin_Chapter1_1st:true},
	jump, "Calvin",
		
	label, "Calvin",
	actor, {id:"Mayor", show:false},
	actor, {id:"Constable", show:false},
	actor, {id:"Detective_Main", show:false},
	//actor, {id:"Detective_Main", nick:"Hawkshaw", color: "#f5f5f5", sprite:["MC", "Character Sprites/Final/DetectiveNeutralResize.png", "FLOOR"], position: "left"},
	//actor, {id:"Mayor", nick:"M. Calvin", color: "#f5f5f5", sprite:["M_Main", "Character Sprites/Final/MayorNeutralResize.png", "FLOOR"], position: "right"},
	macro, "change_to_Dialogue",
	actor, {id:"Detective_Main", show:true, say:"I need to speak with you, Mayor."},
	actor, {id:"Mayor", show:true, say:"Anything I can do to help out famous detective Hawkshaw! Are you sure you don’t want any tea?"},
	actor, {id:"Detective_Main", say:"Quite."},
	label, "CalvinFirstSelection",
	macro, "change_to_Menu",
	menu, ["Select",
		"Relationship", "mayorRelationship",
		"Day of her death", "mayorDayDeath",
		"I'm done with you", "interrogationSelect"],
		
	label, "mayorRelationship",
	macro, "change_to_Dialogue",
	actor, {id:"Detective_Main", say:"How was your marriage with Rachel Lind?"},
	actor, {id:"Mayor", show:false},
	actor, {id:"Constable", show:true, position:"right", say:"Detective! You can't just ask people that--"},
	actor, {id:"Constable", show:false},
	actor, {id:"Mayor", show:true},
	actor, {id:"Mayor", say:"We’ve been married for some years...my happiest days of my life were being married to her!  She was such a wonderful cook and she loved to garden... oh, she was so happy when she gardened... *sniffle*"},
	macro, "change_to_Thought",
	actor, {id:"Detective_Main", say:"(This isn’t getting me anywhere.)"},
	macro, "change_to_Menu",
	menu, ["Select",
		"Back to other questions", "CalvinFirstSelection",
		"Press for more info", "CalvinPressContinue"],
	label, "CalvinPressContinue",
	macro, "change_to_Dialogue",
	actor, {id:"Detective_Main", say:"I need more information, Mayor Bungle."},
	actor, {id:"Mayor", say:"Oh, of course...this sort of thing isn't very useful to you right now.  Ah, but she was such a good wife!  And she was a great mother to Aldwin as well!  Wasn’t she, boy?"},
	actor, {id:"Detective_Main", say:"Mayor Bungle, we need to stay on task."},
	actor, {id:"Mayor", say:"Right, right, of course...... well, we had a great marriage! She was everything I could ask for!"},
	macro, "change_to_Thought",
	actor, {id:"Detective_Main", say:"(Either he’s hopelessly naive or there really wasn’t anything wrong with their marriage. I had better ask for something else.)"},
	macro, "change_to_Dialogue",
	jump, "CalvinFirstSelection",


	label, "mayorDayDeath",
	macro, "change_to_Dialogue",
	actor, {id:"Detective_Main", say:"Could you describe your wife’s behavior leading to her death?"},
	actor, {id:"Mayor", show:false},
	actor, {id:"Constable", show:true, position:"right"},
	actor, {id:"Constable", say:"Uh, Detective? I don’t think that’s a good--"},
	actor, {id:"Detective_Main", say:"Mr. Bungle, if this is how you’re going to treat my investigation, I think I might assign you off the case."},
	actor, {id:"Constable", show:false},
	actor, {id:"Mayor", show:true},
	actor, {id:"Mayor", say:"Now now, no need for that. I’ll answer any questions the great Detective has. Ma’am, go on."},
	actor, {id:"Detective_Main", say:"*Sigh* Was there any... unusual behaviour of your wife on the day of her demise?"},
	actor, {id:"Mayor", say:"No. She seemed perfectly fine!"},
	actor, {id:"Detective_Main", say:"Think hard, Mayor. Are you sure there was no suspicious behavior at the time of her death?"},
	actor, {id:"Mayor", say:" I, uhm... nope. Nothing."},
	macro, "change_to_Menu",
	menu, ["Select",
		"Accuse the mayor of lying", "mayorLie",
		"Present some evidence to the mayor", "mayorEvidence"],
		
	label, "mayorLie",
	macro, "change_to_Dialogue",
	actor, {id:"Detective_Main", say:"You’re holding something back, mayor. Perhaps a fight?"},
	actor, {id:"Mayor", say:"M-My, that’s a brash accusation! Why would I fight with such a lovely lady?"},
	actor, {id:"Detective_Main", say:"You tell me."},
	actor, {id:"Mayor", say:" I-I didn’t! Oh please stop, you’re worrying me!"},
	actor, {id:"Mayor", show:false},
	actor, {id:"Constable", show:true},
	actor, {id:"Constable", say:"Detective, please."},
	macro, "change_to_Thought",
	actor, {id:"Detective_Main", say:"(...I wasn’t expecting such a reaction... oh, I hate how fragile people can be...)"},
	macro, "change_to_Dialogue",
	jump, "CalvinFirstSelection",
	
	label, "mayorEvidence",
	set, {correctitem2:true},
	set, {activescene2:false},
	set, {activescene3:true},
	set, {interrogationmode:true},
	cform, ["interface", true,
	button, {name: "PopJournal", x:35, y: 0, w: 75, h: 76, base:"Images/journal_icon.png",
		link:[jump, "InventoryOpen"], showText: false},],
	jump, "mayorEvidence",
	label, "Datebook_Clicked",
	macro, "change_to_Dialogue",
	actor, {id:"Detective_Main", say:"Can you account for your wife’s whereabouts between seven and eight am on the morning of her death?"},
	actor, {id:"Mayor", say:" I... what? S-She went somewhere that early?"},
	actor, {id:"Detective_Main", say:"You tell me."},
	actor, {id:"Mayor", say:"I... well, she was probably meeting with... one of her charities."},
	actor, {id:"Detective_Main", say:"Why isn’t it written down then?"},
	actor, {id:"Mayor", say:"I... I don’t know. I was working in my office... I met her for breakfast at nine in the morning... I didn’t even know she had stepped out."},
	set, {interrogationmode:false},
	set, {correctitem2:false},
	jump, "interrogationSelect",
	
	label, "Wrong_Datebook",
	actor, {id:"Mayor", say:"What does this have to do with my wife?"},
	macro, "change_to_Thought",
	actor, {id:"Detective_Main", say:"Hmm, I must not be using the right evidence.."},
	macro, "change_to_Dialogue",
	jump, "CalvinFirstSelection",
	
	label, "End_Interrogation_0",
	macro, "change_to_Dialogue",
	actor, {id:"Detective_Main", show:false},
	actor, {id:"Mayor", show:false},
	actor, {id:"Constable", show:false},
	jump, {inter_People_Total:2, label:"End_Interrogation_1"},
	macro, "change_to_Thought",
	actor, {id:"Detective_Main", show:false, say:"(I haven't interviewed enough people yet...)"},
	jump, "interrogationSelect",
	
	label, "End_Interrogation_1",
	macro, "change_to_Dialogue",
	box, {pos:"bottom", back:"image"},
	actor, {id:"Detective_Main", show:true, say:"I think I know where to go from here."},
	actor, {id:"Mayor", show:true, say:"You do? Really?"},
	actor, {id:"Detective_Main", say:"There is more than evidence to suggest that your wife was murdered...and she met with someone before the time of her death that neither of you seem to be aware of. If you'll excuse me..."},
	actor, {id:"Mayor", show:false},
	actor, {id:"Constable", show:true, position:"right", say:"...you mean 'us' right?"},
	actor, {id:"Detective_Main", say:"...I suppose."},
	actor, {id:"Constable", say:"You'll get used to it, Detective Hawkshaw. Where are we headed? I can show you the way."},
	actor, {id:"Detective_Main", show:false},
	actor, {id:"Constable", show:false},
	box, {show:false},

	set, {current_Location:"Foyer"},
	set, {Kitchen_1st_Time:false},
	set, {Town_Streets_1st_Time:false},
	set, {Dining_Hall_1st_Time:false},
	set, {broken_Cup_clicked:false},
	set, {Maid_1st_Invs:false},
	set, {Pickpocket_1st_Invs:false}, //New
	set, {Pickpocket_encounter:false}, //New
	set, {Pickpocket_End_Variable:false}, //New
	set, {jump_to_Conclusion:false}, //New
	jump, "Chapter_1_Maps#Mayor_Mansion_Map_0",
	
	
	//Maid Interrogation goes here. Not yet implemented but should follow similar style to the first one
	//Andy, if you want, you can do this for me. I'll help out tomorrow.
	label, "Maid_Interrogation",
	box, {pos:"bottom", back:"image"},
	actor, {id:"Detective_Main", show:true, position:"left"},
	actor, {id:"Maid", show:true, position:"right"},
	actor, {id:"Detective_Main", say:"Excuse me, Miss...?"},
	actor, {id:"Maid", say:"Leah."},
	actor, {id:"Detective_Main", say:"Miss Leah. I need to ask you a few questions."},
	actor, {id:"Maid", say:"Really? Can it wait? I'm kind of busy..."},
	actor, {id:"Detective_Main", say:"Not really, no."},
	actor, {id:"Maid", say:"*Sigh*"},
	actor, {id:"Detective_Main", say:"What did you think of Rachel Lind?"},
	actor, {id:"Maid", say:"She paid me, ma'am. Doesn't get much deeper than that."},
	actor, {id:"Detective_Main", say:"How many years did you work for her?"},
	actor, {id:"Maid", say:"Ten, ma'am."},
	actor, {id:"Detective_Main", say:"Ten years...and you have no opinion of her at all?"},
	actor, {id:"Maid", say:"Ah...no. Not really. Look, I work here dawn till dusk. Half days on Sundays. I don't have time to talk to nobody, ma'am. I do my job, then I sleep."},
	text, {value:"\nThe maid has been added to your list of suspects!"},
	set, {suspect3:true},
	label, "Maid_Interrogation_Select",
	set, {activescene1:false, activescene2:false, activescene3:false, activescene4:false, activescene5:true, activescene7:false},
	actor, {id:"Detective_Main", show:true},
	actor, {id:"Maid", show:true},
	macro, "change_to_Menu",
	jump, {clue4:true, label:"FullMaidMenu"},
	
	label, "MaidMenu",
	menu, ["Select",
			"Ask about Mayor's Wife", "Question_Rachel",
			"Ask about where she was last seen", "Question_Last_Seen",
			"Ask about her last meal", "Question_Last_Meal",
			"End Interrogation", "Maid_End"],	
	jump, "MaidMenu",
	label, "FullMaidMenu",
	menu, ["Select",
			"Ask about Mayor's Wife", "Question_Rachel",
			"Ask about where she was last seen", "Question_Last_Seen",
			"Ask about her last meal", "Question_Last_Meal",
			"Present Evidence", "Maid_Present_Evidence_Glass",
			"End Interrogation", "Maid_End"],
	jump, "FullMaidMenu",
	
	label, "Question_Rachel",
	macro, "change_to_Dialogue",
	actor, {id:"Detective_Main", show:true, say:"Even if you were busy, after ten years you'd probably know your employer better than anyone.  Everyone else in this town seems to adore her."},
	actor, {id:"Maid", show:true, say:"They did."},
	actor, {id:"Detective_Main", say:"What did you think of her?"},
	actor, {id:"Maid", say:" I think she paid me well enough, ma'am."},
	actor, {id:"Detective_Main", say:"That's it?"},
	actor, {id:"Maid", say:"Mmhmm."},
	label, "Question_Rachel_2",
	macro, "change_to_Menu",
	menu, ["Select", 
			"Press for more information", "Decide_Maid",
			"Back to previous set of questions", "Maid_Interrogation_Select"],
	
	label, "Decide_Maid",
	jump, {Pickpocket_encounter:false, label:"Maid_Info_A"},
	jump, "Maid_Info_B",
	
	label, "Maid_Info_A",
	macro, "change_to_Thought",
	actor, {id:"Detective_Main", say:"(I don't think I'll get much information from her right now.)"},
	jump, "Maid_Interrogation_Select",
	
	label, "Maid_Info_B",
	macro, "change_to_Dialogue",
	actor, {id:"Detective_Main", say:"Listen, Miss Leah, you may have been busy but you had to have an opinion on Rachel Lind."},
	actor, {id:"Maid", say:"Yeah, sure. She was nice."},
	actor, {id:"Detective_Main", say:"Was she?"},
	actor, {id:"Maid", say:"Sure everyone in town's told you the same."},
	actor, {id:"Detective_Main", say:"Most people. Not everyone."},
	actor, {id:"Maid", say:"Guess everyone's got enemies."},
	actor, {id:"Detective_Main", say:"And does she have enemies?"},
	actor, {id:"Maid", say:"I... I 'unno, ma'am. I don't go sticking my nose where it don't belong."},
	actor, {id:"Detective_Main", say:"You probably noticed things, though."},
	actor, {id:"Maid", say:"I... no, nothing out of the ordinary, ma'am."},
	label, "Maid_Lying_Select",
	macro, "change_to_Menu",
	menu, ["Select",
			"You're lying...", "Maid_Lying",
			"Back to previous set of questions", "Maid_Interrogation_Select",
			],
	
	label, "Maid_Lying",
	macro, "change_to_Dialogue",
	actor, {id:"Detective_Main", say:"You're lying. Tell me what you're hiding."},
	actor, {id:"Maid", say:"I... I ain't hiding nothing, ma'am."},
	actor, {id:"Detective_Main", say:"I'm not an idiot, Miss Leah, and I'm hoping you aren't either. Now tell me what it is you've seen."},
	actor, {id:"Maid", say:"I-I could lose my job, ma'am..."},
	actor, {id:"Detective_Main", show:false},
	actor, {id:"Constable", sprite:"C_Main_2", position:"left"},
	actor, {id:"Constable", say:"Hawkshaw... lighten up. Look, Leah, I promise you, you're not going to lose your job. No matter what you tell us, my father will listen to me. All right? Just tell us what happened."},
	actor, {id:"Maid", say:"I... okay. Look, the lady was nice enough to people like her, you know? Her rich friends at the parties, people who have the nice dresses and clothes, people who have time to learn how to be fancy."},
	actor, {id:"Maid", say:"But the folks who work... or worse, the ones who don't... well. She isn't too fond of them."},
	actor, {id:"Constable", show:false}, 
	actor, {id:"Detective_Main", show:true},
	actor, {id:"Detective_Main", say:"How so?"},
	actor, {id:"Maid", say:" I know she's charitable and all, but those people she helps... she doesn't have much love for 'em. If you're working, if you've got a respectable job... you're okay then. But she talks a whole lot about which jobs are which."},
	actor, {id:"Maid", say:"If you're a constable, you've got your life figured out well enough, though you're a little unambitious... sorry, Aldwin."},
	actor, {id:"Detective_Main", show:false},
	actor, {id:"Constable", show:true, say:"It's no problem."}, //Its no problem.
	actor, {id:"Maid", say:"Honestly... I never got the sense she was too fond of me. Always was a bit short with me, you know, but she could've been worse. Lately, though... I dunno. There's been something different about her."},
	actor, {id:"Constable", sprite:"C_Main", position:"right", show:false},
	//actor, {id:"Constable", nick:"Aldwin B.", color:"#f5f5f5", sprite:["C_Main", "Character Sprites/Final/ConstableResize.png", "FLOOR"], position:"right", show:false}, 
	actor, {id:"Detective_Main", show:true},
	actor, {id:"Detective_Main", say:"Different how?"},
	actor, {id:"Maid", say:"Always angry, always picking fights. Whenever her lady friends were over, all she'd do is complain about the 'working class slobs' who don't want to help themselves."},
	actor, {id:"Maid", say:"The worst was after she came back from a charity event. She was furious. I think she got pickpocketed, but I'm not sure."},
	actor, {id:"Maid", say:"She was fuming though, raving about all of the ingrates who took her money and wasted it away drinking and whoring instead of trying to find respectable work, or shoving out more children than they could feed."},
	actor, {id:"Maid", say:"And... well, she might've been a little drunk... but..."},
	actor, {id:"Detective_Main", say:"But what?"},
	actor, {id:"Maid", say:"She... might've mentioned something about the charity. About how if they weren't going to put it to good use, then she wasn't going to waste it on them. I don't know if she went ahead and did anything, though..."},
	actor, {id:"Detective_Main", say:"I see. Thank you, Miss Leah."},
	set, {jump_to_Conclusion:true},
	jump, "Maid_Interrogation_Select",
	
	label, "Question_Last_Seen",
	macro, "change_to_Dialogue",
	actor, {id:"Detective_Main", say:"When did you last see Rachel Lind?"},
	actor, {id:"Maid", say:"It was just before breakfast, ma'am. I'd just set the table and she'd just walked in. I'd gone off to do some cleaning in the study, before I heard the mayor screeching. When I ran back to the dining room, she was already... er... gone."},
	actor, {id:"Detective_Main", say:"Meaning she was dead?"},
	actor, {id:"Maid", say:"Uh, yes, ma'am."},
	jump, "Maid_Interrogation_Select",
	
	label, "Question_Last_Meal",
	macro, "change_to_Dialogue",
	actor, {id:"Detective_Main", say:"Are you aware that Rachel Lind was poisoned?"},
	actor, {id:"Maid", say:"Poison? I... but... they said she... oh God, you don't mean to think I did it, do you?"},
	actor, {id:"Detective_Main", say:"That depends. How did the poison get in her food?"},
	actor, {id:"Maid", say:"It... it didn't! I mean, I didn't put it there..."},
	actor, {id:"Detective_Main", say:"Who did?"},
	actor, {id:"Maid", say:"I don't know!"},
	actor, {id:"Detective_Main", say:"Don't you prepare the food?"},
	actor, {id:"Maid", say:"Yes, I do... but..."},
	actor, {id:"Detective_Main", say:"What were you serving?"},
	actor, {id:"Maid", say:"The usual... eggs, bread, bacon, tea, you know..."},
	actor, {id:"Detective_Main", say:"How do you prepare the tea?"},
	actor, {id:"Maid", say:" Actually, the Mistress grows a few of the ingredients, ma'am. Otherwise, she keeps a few things in stock. She tells me what to use and I do it."},
	actor, {id:"Detective_Main", say:"You don't know which plant is which, then?"},
	actor, {id:"Maid", say:"Well, they've all got labels."},
	label, "Maid_Show_Evidence_Hemlock",
	macro, "change_to_Menu",
	menu, ["Select", 
			"Return to questions", "Maid_Interrogation_Select",
			"Present Evidence", "Maid_Present_Evidence_Hemlock",
			],
	
	label, "Maid_Present_Evidence_Hemlock",
	macro, "change_to_Dialogue",
	set, {correctitem2:false, correctitem3:true, correctitem4:false, activescene3:false, activescene4:true, interrogationmode:true},  
	cform, ["Inventory", true,
				button, {name:"PopJournal", x:100, y:0, w:75, h:76, base:"Images/journal_icon.png",
				link:[jump, "InventoryOpen"], showText: false}],
	jump, "Maid_Present_Evidence_Hemlock",
	//Access to Journal and presenting Hemlock. CorrectItem3:true
	
	
	label, "Hemlock_Clicked",
	set, {correctitem3:false},
	set, {activescene1:false, activescene2:false, activescene3:false, activescene4:true, activescene5:false},
	macro, "change_to_Dialogue",
	actor, {id:"Detective_Main", say:"Anything like this?"},
	actor, {id:"Maid", say:"I... look, they're all plants to me, ma'am. She was the one that spent every day with 'em. I just turned them into tea for her. Might be, sure."},
	actor, {id:"Detective_Main", say:"I see..."},
	jump, "Maid_Interrogation_Select",
	
	label, "Wrong_Hemlock",
	set, {activescene1:false, activescene2:false, activescene3:false, activescene4:true, activescene5:false},
	actor, {id:"Detective_Main", say:"Anything like this?"},
	actor, {id:"Maid", say:"Wait, what are you trying to show me?"},
	macro, "change_to_Thought",
	actor, {id:"Detective_Main", say:"(I thought I was on the right track...I suppose not.)"},
	macro, "change_to_Dialogue",
	jump, "Maid_Interrogation_Select",

	label, "Maid_Glass_Clicked",
	macro, "change_to_Dialogue",
	actor, {id:"Detective_Main", say:"There's a broken glass here in the kitchen. Rather strange, considering how spotless the rest of the house is..."},
	actor, {id:"Maid", say:"O-oh. That. I, ah, just haven’t gotten around to throwing that out..."},
	actor, {id:"Detective_Main", say:"What is it doing here to begin with?"},
	actor, {id:"Maid", say:"I... really shouldn’t be saying, ma’am."},
	actor, {id:"Detective_Main", show:false},
	actor, {id:"Constable", sprite:["faceright", "Character Sprites/Final/ConstableNeutralResizeFlipped.png"], position:"left", say:"It's fine, Leah."},
	actor, {id:"Constable", sprite:"C_Main", position:"right", show:false},
	actor, {id:"Detective_Main", show:true},
	actor, {id:"Maid", say:"Well... fine then. That wasn’t one of Mrs. Bungle’s finer moments, I’d say. If it was my place to say, I mean. All it took was for Aldwin to mention his work for her to start howling about the 'worthless leeches' in society, and how much they were costing her."},
	actor, {id:"Maid", say:"It wasn’t a pretty sight, I’ll tell you. She broke the glass she was holding and all. She told me to clean it up, but ordered me away before I could get all of it."},
	actor, {id:"Maid", say:"I just knew that if she cut herself, I’d get the sack. She was right scary that evening, I dunno what set her off."},
	actor, {id:"Detective_Main", say:"I see. Thank you."},
	set, {maidGlassShown:true},
	set, {interrogationmode:false},
	actor, {id:"Constable", show:false},
	jump, "Maid_Interrogation_Select",
	
	label, "Maid_Present_Evidence_Glass",
	macro, "change_to_Dialogue",
	set, {interrogationmode:true},
	set, {correctitem4:true, correctitem3: false},
	set, {correctitem2:false, correctitem1:false},
	set, {activescene6:true, activescene5:false},
	set, {activescene4:false, activescene3:false, activescene2:false, activescene1:false},
	cform, ["interface", true,
	button, {name: "PopJournal", x:35, y: 0, w: 75, h: 76, base:"Images/journal_icon.png",
		link:[jump, "InventoryOpen"], showText: false}],
	jump, "Maid_Present_Evidence_Glass",
	
	label, "Maid_Wrong_Glass",
	macro, "change_to_Dialogue",
	actor, {id:"Detective_Main", say:"Is there anything you can tell me about this?"},
	actor, {id:"Maid", say:"What, that? What is that?"},
	macro, "change_to_Thought",
	actor, {id:"Detective_Main", say:"(Guess not.)"},
	macro, "change_to_Dialogue",
	jump, "Maid_Interrogation_Select",
	
	label, "Maid_End",
	macro, "change_to_Dialogue",
	actor, {id:"Detective_Main", say:"This should be it, for now. If I need anything else I'll return."},
	actor, {id:"Maid", say:"Great..."},
	box, {show:false},
	label, "Maid_Idle",
	actor, {id:"Detective_Main", show:false},
	actor, {id:"Maid", position:"center"},
	jump, "Chapter_1_Maps#General_Interface",
	
	label, "Maid_2nd",
	box, {pos:"bottom", back:"image"},
	actor, {id:"Maid", position:"right"},
	actor, {id:"Detective_Main", show:true, say:"I'm back and I need to ask you questions again."},
	actor, {id:"Maid", say:"Hmph..."},
	jump, "Maid_Interrogation_Select",
	/*
	actor, {id:"Detective_Main", say:"Excuse me, Miss...?"},
	actor, {id:"Maid", say:"Leah."},
	actor, {id:"Detective_Main", say:"Excuse me, Miss...?"},
	actor, {id:"Maid", say:"Leah."},
	*/
	
	label, "Mayor_Foyer_Interact",
	
	////////////////////////
	label, "Pickpocket_1st_Event",
	set, {Pickpocket_Coin_Event:false},
	box, {pos:"bottom", back:"image"},
	actor, {id:"Detective_Main", show:true, position:"left", say:"...Well, this is highly annoying."},
	actor, {id:"Constable", sprite:"C_Main", position:"right", show:true, say:"The folk here are very religious, ma-- uh, Detective Hawkshaw. We can try again in a few hours."},
	actor, {id:"Detective_Main", say:"The killer hasn’t covered their tracks up in a few days, I suppose they won’t be able to in a few more hours."},
	actor, {id:"Detective_Main", show:false},
	actor, {id:"Constable", show:false},
	box, {show:false},
	screen, {shake:10, duration:1}, //Shakes the screen with an amplitude of 10 for 2 seconds
	box, {show:true},
	actor, {id:"Pickpocket", nick:"??????", position:"right", show:false, say:"...Heheh...got it!"},
	actor, {id:"Constable", show:true, say:" Little boy, you should watch where you’re going!"},
	actor, {id:"Constable", say:"... Detective? Are you okay?", append:true},
	actor, {id:"Detective_Main", show:true, say:"...Go catch that little boy, Constable."},
	actor, {id:"Constable", say:"W-What? Er...okay..."},
	actor, {id:"Constable", show:false, say: "Come along, kid! The lady just needs to ask you a few--augh!"},
	actor, {id:"Pickpocket", nick:"??????", show:false, say: "Hah! Nice try, old man!  You can't--hey!"},
	actor, {id:"Constable", show:true, say:"Got him!"},
	actor, {id:"Constable", show:false},
	actor, {id:"Pickpocket", nick:"??????", show:true, position:"right", say:"Hey, what’re you doin’?! Let me go, you copper!"},
	actor, {id:"Detective_Main", say:"..."},
	//actor, {id:"Pickpocket", show:false},
	label, "Pickpocket_Menu_1",
	macro, "change_to_Menu",
	actor, {id:"Detective_Main", show:true},
	actor, {id:"Pickpocket", show:true},
	menu, ["Select what to do to the Pickpocket",
			"Search his pockets", "Pickpocket_Pocket",
			"Remove his Hat", "Pickpocket_Hat"],
			
	label, "Pickpocket_Pocket",
	macro, "change_to_Dialogue",
	actor, {id:"Pickpocket", nick:"??????", show:true, say:"You blimey lily-livered--!"},
	actor, {id:"Detective_Main", show:true, say:"*Sigh* Lint."},
	actor, {id:"Pickpocket", show:false},
	actor, {id:"Constable", show:true, say:"Uh, what is it that you’re searching for, Detective? He’s squirming like a bug, so maybe if you could wrap this up?"},
	actor, {id:"Constable", show:false},
	jump, "Pickpocket_Menu_1",
	
	label, "Pickpocket_Hat",
	macro, "change_to_Dialogue",
	actor, {id:"Detective_Main", show:true, say:"Remove the pickpocket’s hat, Constable."},
	actor, {id:"Pickpocket", nick:"??????", show:false},
	actor, {id:"Constable", show:true, say:"Okay..."},
	actor, {id:"Constable", say:"I found something. Seems to be a coin purse. Is it yours, Detective?"},
	actor, {id:"Detective_Main", say:"Yes it is."},
	actor, {id:"Constable", show:false},
	actor, {id:"Pickpocket", show:true},
	actor, {id:"Detective_Main", say:"Don’t try to steal from a detective, little boy. Now, what is the sentence for a common thief around these parts?"},
	actor, {id:"Pickpocket", nick:"??????", say:"I won’t go back to the workhouse! You can’t make me!"},
	actor, {id:"Pickpocket", show:false},
	actor, {id:"Constable", show:true, say:"Detective, be reasonable. Surely there’s something else we can do...?"},
	actor, {id:"Detective_Main", say:"I don’t see what else is to be done with a common thief. A thief dumb enough to be caught, no less."},
	actor, {id:"Constable", show:false},
	actor, {id:"Pickpocket", nick:"Dipper", show:true, say:"The name's Dipper! And I'm not dumb! Just try me!"},
	actor, {id:"Detective_Main", say:"Oh really?"},
	text, {speaker:" ", value:"You have added Dipper the Pickpocket into your suspect list!"},
	set, {suspect4:true},
	label, "Pickpocket_Interrogation_Select",
	macro, "change_to_Menu",
	actor, {id:"Detective_Main", show:true},
	actor, {id:"Pickpocket", show:true},
	menu, ["List of Suspects. Click who to ask the Pickpocket about.",
			"Mayor", "Pickpocket_Mayor",
			"Maid", "Pickpocket_Maid",
			"Constable", "Pickpocket_Constable",
			"Mayor's Wife", "Pickpocket_Mayor's_Wife_Decide",
			"End Interrogation", "Pickpocket_End_Decide",
			],
			
	label, "Pickpocket_Mayor's_Wife_Decide",
	jump, {Pickpocket_Coin_Event:false, label:"Pickpocket_Mayor's_Wife"},
	jump, "Pickpocket_Interrogation_Select_2",
	
	label, "Pickpocket_End_Decide",
	jump, {Pickpocket_End_Variable:true, label:"Pickpocket_End_2"},
	jump, "Pickpocket_End",
	
	label, "Pickpocket_Mayor",
	macro, "change_to_Dialogue",
	actor, {id:"Detective_Main", show:true, say:"What can you tell me about the Mayor?"},
	actor, {id:"Pickpocket", show:true, say:"I’unno. He’s the mayor, I guess. Don’t matter to me."},
	actor, {id:"Detective_Main", show:true, say:"... You’re not proving your usefulness."},
	actor, {id:"Pickpocket", show:true, say:" I am too! You’re just asking stupid questions! Just try me!"},
	actor, {id:"Detective_Main", show:true, say:"*Sigh*"},
	jump, "Pickpocket_Interrogation_Select",
	
	label, "Pickpocket_Maid",
	macro, "change_to_Dialogue",
	actor, {id:"Detective_Main", show:true, say:"What can you tell me about the Maid at the Mayor's Manor?"},
	actor, {id:"Pickpocket", show:true, say:"Nothin’. I don’t know who she is-- wait... is she the grumpy pigeon lady?"},
	actor, {id:"Detective_Main", show:true, say:"No."},
	actor, {id:"Pickpocket", show:true, say:"Then I got nothin’."},
	actor, {id:"Detective_Main", show:true, say:"You’re a very smart lad."},
	actor, {id:"Pickpocket", show:true, say:"Heeey! C’mon, try me!"},
	jump, "Pickpocket_Interrogation_Select",
	
	label, "Pickpocket_Constable",
	macro, "change_to_Dialogue",
	actor, {id:"Detective_Main", show:true, say:"Can you tell me anything about him?"},
	actor, {id:"Pickpocket", show:false},
	actor, {id:"Constable", position:"right", sprite:"C_Main", show:true, say:"Uh... Detective? I'm right here."},
	actor, {id:"Constable", show:false},
	actor, {id:"Pickpocket", show:true, say:"What, you think I’m gonna rat on a copper? I’m smarter than that, lady!"},
	macro, "change_to_Thought",
	actor, {id:"Detective_Main", say:"(Maybe I should wait for the Constable to not be around me before I try this line of questioning...)"},
	jump, "Pickpocket_Interrogation_Select",
	
	label, "Pickpocket_Mayor's_Wife",
	set, {Pickpocket_Coin_Event:true},
	macro, "change_to_Dialogue",
	actor, {id:"Detective_Main", show:true, say:"Can you tell me anything about her?"},
	actor, {id:"Pickpocket", show:true, say:"... Maaaybe..."},
	actor, {id:"Detective_Main", show:true, say:"*Sigh* Constable, can you do something about this?"},
	actor, {id:"Pickpocket", show:false},
	actor, {id:"Constable", show:true, say:"Of course, Detective."},
	actor, {id:"Detective_Main", show:false},
	actor, {id:"Constable", position:"left", sprite:["C_Main_2", "Character Sprites/Final/ConstableNeutralResizeFlipped.png", "FLOOR"], say:"Here you go."},
	actor, {id:"Pickpocket", show:true, say:"A coin?! How cheap do you think I am?  Gonna need more than that!"},
	actor, {id:"Constable", say:"...very well..."},
	actor, {id:"Pickpocket", say:"Heheh, thanks gramps!"},
	actor, {id:"Constable", say:"G-Gramps?!"},
	actor, {id:"Pickpocket", say:"Now, what do yah wanna know? Gotta ask the right questions, you know!"},
	actor, {id:"Constable", show:false},
	actor, {id:"Detective_Main", show:true, say:"..."},
	//actor, {id:"Constable", sprite:["C_Main", "Character Sprites/Final/ConstableResize.png", "FLOOR"], position:"right", show:false},
	label, "Pickpocket_Interrogation_Select_2",
	actor, {id:"Detective_Main", show:true},
	actor, {id:"Pickpocket", show:true},
	macro, "change_to_Menu",
	menu, ["Select what to ask the Pickpocket about the Mayor's Wife, Rachel Lind", 
			"When did you last see her?", "Pickpocket_Last_See_Her",
			"What is she like?", "Pickpocket_She_Like",
			"Return to previous set of questions", "Pickpocket_Interrogation_Select",
			],
			
	label, "Pickpocket_Last_See_Her",
	macro, "change_to_Dialogue",
	actor, {id:"Detective_Main", show:true, say:"When do you remember last seeing her?"},
	actor, {id:"Pickpocket", show:true, say:"Uhhh.... I don’t remember."},
	actor, {id:"Detective_Main", say:"... Can you think?"},
	actor, {id:"Pickpocket", say:" I can too think! Look, it was four days ago and in the early morning! I know cause she broke one of her heels on the cobblestone and woke me up!"},
	actor, {id:"Detective_Main", say:"What else happened?"},
	actor, {id:"Pickpocket", say:"Uhhh... she... uh... oh! She walked into the church, and then I went and grabbed her heel. Thought I might sell it to a shoemaker. ... That won’t get me in trouble, will it?"},
	actor, {id:"Detective_Main", say:"Not at all."},
	jump, "Pickpocket_Interrogation_Select_2",
	
	label, "Pickpocket_She_Like",
	macro, "change_to_Dialogue",
	actor, {id:"Detective_Main", show:true, say:"What are your... impressions about the mayor’s wife?"},
	actor, {id:"Pickpocket", show:true, say:"Im...pressions?"},
	actor, {id:"Detective_Main", say:"*Sigh* Do you like her?"},
	actor, {id:"Pickpocket", say:"No. I hate her! She’s mean as piss now!"},
	actor, {id:"Detective_Main", say:"Mean to you? How?"},
	actor, {id:"Pickpocket", say:"Well... She used to give out a bunch of shiny bits like your friend does. If you put on the big puppy eyes she would give double and pat me on the head... She was real nice then."},
	actor, {id:"Detective_Main", say:"She’s not nice anymore?"},
	actor, {id:"Pickpocket", say:"Hell no! She won’t give me any coin, she just yells at me and spits and says that I’m just a street rat. None of the kids go near her now."},
	actor, {id:"Detective_Main", say:"Interesting..."},
	set, {Pickpocket_encounter:true}, //Triggers extra dialogue with the Maid
	macro, "change_to_Thought",
	actor, {id:"Detective_Main", say:"Maybe I should ask the maid about the mayor's wife..."},
	macro, "change_to_Dialogue",
	jump, "Pickpocket_Interrogation_Select_2",
	
	label, "Pickpocket_End",
	macro, "change_to_Dialogue",
	actor, {id:"Detective_Main", show:true, say:"Well, you turned out to be useful after all, thief."},
	actor, {id:"Pickpocket", show:true, say:"Name’s Dipper! And I’m not a thief, I’m a pickpocket. And here’s your coin back, lady."},
	actor, {id:"Detective_Main", say:"......"},
	actor, {id:"Pickpocket", show:false},
	actor, {id:"Constable", sprite:"C_Main", show:true, position:"right", say:"I... guess this is where you say thanks, Detective."},
	actor, {id:"Constable", show:false},
	actor, {id:"Pickpocket", show:true},
	actor, {id:"Detective_Main", show:true, say:"...Thanks Dipper."},
	actor, {id:"Pickpocket", say:"Nighty night, Miss Detective! Good luck on figuring out who killed that lady! Oh, and if you need me, I'll be here!"},
	actor, {id:"Pickpocket", show:false},
	actor, {id:"Constable", show:true},
	actor, {id:"Detective_Main", say:"This town is quite... eccentric."},
	actor, {id:"Constable", say:"Oh, you haven’t seen the half of it yet."},
	actor, {id:"Detective_Main", show:false},
	actor, {id:"Constable", show:false},
	box, {show:false},
	set, {Pickpocket_End_Variable:true},
	jump, "Chapter_1_Maps#Mayor_Mansion_Map_0",
	
	label, "Pickpocket_End_2",
	macro, "change_to_Dialogue",
	actor, {id:"Detective_Main", say:"Thanks again, Dipper."},
	actor, {id:"Pickpocket", say:"No problem."},
	actor, {id:"Detective_Main", show:false},
	actor, {id:"Pickpocket", remove:"actor"},
	box, {show:false},
	jump, "Chapter_1_Maps#Pickpocket_in_town",
	
	
	label, "Pickpocket_Again",
	actor, {id:"Pickpocket", position:"right", show:true, say:"You're back Detective! Wanna ask me questions again?"},
	actor, {id:"Detective_Main", position:"left", show:true, say:"..."},
	jump, "Pickpocket_Interrogation_Select",
	
	label, "Chapter_1_Conclusion",
	//text, {value:"\nAre we here?",},
	scene, {src:"Background Images/Final/town_color01.jpg", effect:"dissolve"},
	audio, {bgm:"Music/town", format:["ogg"]},	
	box, {pos:"bottom", back:"image"},
	actor, {id:"Constable", sprite:"C_Main", position:"right", show:true, say:"It’s getting late, Detective Hawkshaw."},
	actor, {id:"Detective_Main", show:true, say:"Is it? Mn... I didn’t even notice."},
	actor, {id:"Constable", say:"The rest of the town citizens are going to be eating dinner and then heading to bed.  It would be considered rude of you to wake them up."},
	actor, {id:"Detective_Main", say:"Well I wasn’t about to do that... I need a few more clues before I can start yanking people out of their beds in the middle of the night."},
	actor, {id:"Constable", say:"...I can never quite tell when you’re joking."},
	actor, {id:"Detective_Main", say:"It takes time. Now, I shall let you get some rest."},
	actor, {id:"Constable", say:"Do you even know where you’re going, Detective?"},
	actor, {id:"Detective_Main", say:"The town is small, Constable. I could walk it three times over in less than an hour."},
	actor, {id:"Constable", say:"Let me spare you the hour and just show you where you’re staying at."},
	actor, {id:"Detective_Main", say:"... *Sigh* If you insist."},
	actor, {id:"Detective_Main", show:false},
	actor, {id:"Constable", remove:"actor"},
	box, {show:false},
	scene, {src:"Background Images/Final/study_color_lineless01.jpg", effect:"dissolve"},
	audio, {bgm:"Music/title", format:["ogg"]},
	box, {show:true},
	macro, "change_to_Thought",
	actor, {id:"Detective_Main", show:true, position:"center", say:"Just as I thought... this town is backwater enough to put all those yankees to shame. There’s something else going on in this town... something darker. God willing, I’ll get to the bottom of this before it’s too late."},
	box, {show:false},
	actor, {id:"Detective_Main", remove:"actor"},
	
	//To be Continued Screen or End of Stable Game
	scene, {src:"black", effect:"dissolve"},
	box, {pos:"center", back:"none"},
	macro, "change_to_Title",
	text, {align:"center", value:"End of Chapter 1...\nTO BE CONTINUED", effect:"fade", duration:0},
	
	
];

