journal = [
	label, "journalShow",
	//REMEMBER NUMFORMS IS NOW A RUNNING COUNT, NOT A BOOLEAN
	//set, {numForms:0},
	box, {show: false},
	macro, "change_to_Dialogue",
	text, {value:"\nThis is my journal.  I keep everything I know about my case in here, including a list of suspects and notes about clues."},
	text, {value:"\nFor now, what I need is some physical evidence."},
	label, "journalon",
	overlay, {src:"Images/barframe2_50.png", effect:"ghost"},
	box, {show: false},
	label, "journalScreen",
	set, {buttonclick:true},
	set, {inventoryup:false},
	set, {suspectup:false},
	set, {letterselect:false},
	set, {datebookselect:false},
	set, {hemlockselect:false},
	set, {glassselect:false},
	set, {itemselected:false},
	set, {numForms:2},
	cform, ["journalMain", true,
		button, {name:"inventory", x:20, y: 60, w: 97, h: 98, base:"Images/clueIcon.png",
			link:[jump, {inventoryup:false, buttonclick:true, label:"clues1"}], showText: false},
		button, {name:"closeJournal", x:645, y:0, w:75, h:76, base:"Images/BackIcon.png",
			link:[jump, "back"], showText: false},
		button, {name:"suspects", x:20, y: 160, w:97, h: 98, base:"Images/SuspectIcon.png",
			link:[jump, {suspectup:false, buttonclick:true, label:"suspectList1"}], showText: false},
	],
	jump, "journalScreen",
	
	label, "clues1",
	box, {show:false},
	set, {inventoryup:true},
	jump, {suspectup:false, label: "cluesCreate"},
	jump, {numForms:2, label: "cluesCreate"},
	cform, "close",
	set, {numForms:"+1"},
	jump, "clues1",

	label, "cluesCreate",
	set, {suspectup:false},
	jump, {clue4:true, label:"button4"},
	jump, {clue3:true, label:"button3"},
	jump, {clue2:true, label:"button2"},
	jump, {clue1:true, label:"button1"},
	label, "clues2",
	box, {show:false},
	label, "idleclues",
	set, {buttonclick:true},
	macro, "change_to_Dialogue",
	jump,"idleclues",
	
	label, "button1",
	set, {numForms:"-1"},
	cform, ["butt1", true,
		button, {name:"Slot1", x:200, y:80, w:113, h:116, base:"Images/letter_sprite.png", link:[jump, {buttonclick:true, label:"confirmation1"}], showText:false}],
	box, {show:false},
	jump, "clues2",
	label, "confirmation1",
	text, {value:"Item\nThe Mayor's letter, addressed to one Detective Hawkshaw."},
	set, {buttonclick:false},
	box, {show:false},
	jump, {interrogationmode:false, label:"idleclues"},
	label, "menuPop1",
	macro, "change_to_Menu",
	menu, ["Is this the item you want to present?",
		"Yes", "result1",
		"No", "idleclues"],
	jump, "menuPop1",
	jump, "idleclues",
	label, "result1",
	macro, "change_to_Dialogue",
	set, {itemselected:true},
	box, {show:false},
	jump, {correctitem4:true, label:"back"},
	jump, {correctitem3:true, label:"back"},
	jump, {correctitem2:true, label:"back"},
	set, {letterselect:true},
	jump, {correctitem1:true, label:"back"},
	
	label, "button2",
	set, {numForms:"-1"},	
	cform, ["butt2", true,
		button, {name:"Slot1", x:200, y:80, w:113, h:116, base:"Images/letter_sprite.png", link:[jump, {buttonclick:true, label:"confirmation1"}], showText:false},
		button, {name:"Slot2", x:325, y:80, w:113, h:116, base:"Images/DateBookClueResize.png", link:[jump, {buttonclick:true, label:"confirmation2"}], showText:false}],
	jump, "idleclues",
	label, "confirmation2",
	text, {value:"Item\nA datebook found in the dining room belonging to the mayor's late wife."},
	set, {buttonclick:false},
	box, {show:false},
	jump, {interrogationmode:false, label:"idleclues"},
	label, "menuPop2",
	macro, "change_to_Menu",
	menu, ["Is this the item you want to present?",
		"Yes", "result2",
		"No", "idleclues"],
	jump, "menuPop2",
	label, "result2",
	macro, "change_to_Dialogue",
	set, {itemselected:true},
	set, {letterselect:false},
	jump, {correctitem3:true, label:"back"},
	jump, {correctitem4:true, label:"back"},
	set, {datebookselect:true},
	jump, {correctitem2:true, label:"back"},

	label, "button3",
	set, {numForms:"-1"},	
	cform, ["butt3", true,
		button, {name:"Slot1", x:200, y:80, w:113, h:116, base:"Images/letter_sprite.png", link:[jump, {buttonclick:true, label:"confirmation1"}], showText:false},
		button, {name:"Slot2", x:325, y:80, w:113, h:116, base:"Images/DateBookClueResize.png", link:[jump, {buttonclick:true, label:"confirmation2"}], showText:false},
		button, {name:"Slot3", x:450, y:80, w:113, h:116, base:"Images/HemlockClue.png", link:[jump, {buttonclick:true, label:"confirmation3"}], showText:false}],
	jump, "idleclues",
	label, "confirmation3",
	text, {value:"Item\nA piece of hemlock, discovered in the dining room. Could it possibly have been used to murder Rachel Lind?"},
	set, {buttonclick:false},
	box, {show:false},
	jump, {interrogationmode:false, label:"idleclues"},
	label, "menuPop3",
	macro, "change_to_Menu",
	menu, ["Is this the item you want to present?",
		"Yes", "result3",
		"No", "idleclues"],
	jump, "menuPop3",
	label, "result3",
	macro, "change_to_Dialogue",
	set, {itemselected:true},
	jump, {correctitem2:true, label:"back"},
	jump, {correctitem4:true, label:"back"},
	set, {hemlockselect:true},
	jump, {correctitem3:true, label:"back"},
	
	label, "button4",
	set, {numForms:"-1"},	
	cform, ["butt4", true,
		button, {name:"Slot1", x:200, y:80, w:113, h:116, base:"Images/letter_sprite.png", link:[jump, {buttonclick:true, label:"confirmation1"}], showText:false},
		button, {name:"Slot2", x:325, y:80, w:113, h:116, base:"Images/DateBookClueResize.png", link:[jump, {buttonclick:true, label:"confirmation2"}], showText:false},
		button, {name:"Slot3", x:450, y:80, w:113, h:116, base:"Images/HemlockClue.png", link:[jump, {buttonclick:true, label:"confirmation3"}], showText:false},
		button, {name:"Slot4", x:200, y:200, w:113, h:116, base:"Images/brokenGlass.png", link:[jump, {buttonclick:true, label:"confirmation4"}], showText:false}],
	jump, "idleclues",
	label, "confirmation4",
	text, {value:"Item\nA broken glass, found in the kitchen."},
	set, {buttonclick:false},
	jump, {maidGlassShown:false, label:"maidGlass"},
	text, {value:"It doesn't seem to have been broken recently. Who was the culprit?", append:true},
	label, "maidGlass",
	box, {show:false},
	jump, {interrogationmode:false, label:"idleclues"},
	label, "menuPop4",
	macro, "change_to_Menu",
	menu, ["Is this the item you want to present?",
		"Yes", "result4",
		"No", "idleclues"],
	jump, "menuPop4",
	label, "result4",
	macro, "change_to_Dialogue",
	set, {itemselected:true},
	jump, {correctitem3:true, label:"back"},
	set, {glassselect:true},
	jump, {correctitem4:true, label:"back"},
	
	label, "back",
	box, {show:false},
	set, {numForms:"+1"},
	jump, {numForms:5, label:"overlayClose"},
	cform, "close",
	jump, "back",
	label, "overlayClose",
	overlay, {effect:"none", show:false},
	jump, {correctitem1:true, activescene1:true, letterselect:true, label:"CHAPTER1#Letter_Clicked"},
	jump, {correctitem2:true, activescene3:true, datebookselect:false, itemselected:true, label:"CHAPTER1#Wrong_Datebook"},
	jump, {correctitem2:true, activescene3:true, datebookselect:true, label:"CHAPTER1#Datebook_Clicked"},
	jump, {correctitem3:true, hemlockselect:false, itemselected:true, label:"CHAPTER1#Wrong_Hemlock"},
	jump, {correctitem3:true, hemlockselect:true, label:"CHAPTER1#Hemlock_Clicked"},
	jump, {correctitem4:true, activescene6:true, itemselected:true, glassselect:false, label:"CHAPTER1#Maid_Wrong_Glass"},
	jump, {correctitem4:true, activescene6:true, itemselected:true, glassselect:true, label:"CHAPTER1#Maid_Glass_Clicked"},
	jump, {activescene1:true, label:"CHAPTER1#Town"},
	jump, {activescene2:true, label:"Chapter_1_Maps#Inv_Scene_1.1"},
	jump, {activescene3:true, label:"CHAPTER1#CalvinFirstSelection"},
	jump, {activescene4:true, label:"CHAPTER1#Maid_Interrogation_Select"},
	jump, {activescene5:true, label:"CHAPTER1#Maid_Idle"},
	jump, {activescene6:true, label:"CHAPTER1#Maid_Interrogation_Select"},
	jump, {activescene7:true, label:"Chapter_1_Maps#Pickpocket_return"},
	
	label, "suspectList1",
	box, {show:false},
	set, {suspectup:true},
	jump, {inventoryup:false, label: "suspectCreate"},
	jump, {numForms:2, label: "suspectCreate"},
	cform, "close",
	set, {numForms:"+1"},
	jump, "suspectList1",

	label, "suspectCreate",
	set, {inventoryup:false},
	jump, {suspect1:false, label:"emptysuspects"},
	jump, {suspect4:true, label:"susp4"},
	jump, {suspect3:true, label:"susp3"},
	jump, {suspect2:true, label:"susp2"},
	jump, {suspect1:true, label:"susp1"},
	label, "idlesuspects",
	jump,"idlesuspects",
	
	//in case someone selects the suspect list before any suspects have been added
	label, "emptysuspects",
	cform, "hide",
	text, {speaker:"Game", value:"You do not have any suspects on your list at the moment."},
	box, {show:false},
	cform, "show",
	jump, "idlesuspects",
	
	label, "susp1",
	set, {numForms:"-1"},
	cform, ["sus1", true,
		button, {name:"Suspect1", x:200, y:90, w:120, h:225, base:"Images/constablethumb.png", 
		link:[jump, "suspectconfirm1"], showText:false}],
	jump, "idlesuspects",
	label, "suspectconfirm1",
	text, {value:"Suspect\nConstable Aldwin Bungle. He is the son of the victim and the Mayor. He seems to get along with everyone in town, but I can't imagine how."},
	box, {show:false},
	jump, {suspectmode:false, label:"idlesuspects"},
	menu, ["Is this the suspect you wish you select?",
		"Yes", "ConstablePick",
		"No", "idlesuspects"],

	label, "susp2",
	set, {numForms:"-1"},
	cform, ["sus2", true,
		button, {name:"Suspect1", x:200, y:90, w:120, h:225, base:"Images/constablethumb.png", 
		link:[jump, "suspectconfirm1"], showText:false},
		button, {name:"Suspect2", x:325, y:90, w:120, h:225, base:"Images/mayorthumb.png", 
		link:[jump, "suspectconfirm2"], showText:false}],
	jump, "idlesuspects",
	label, "suspectconfirm2",
	text, {value:"Suspect\nMayor Calvin Bungle. He is the Mayor of Clandes Town and the husband of the victim. He seems rather upset about the whole ordeal. Understandable, as he only ever saw his wife through rose-tinted lenses."},
	box, {show:false},
	jump, {suspectmode:false, label:"idlesuspects"},
	menu, ["Is this the suspect you wish you select?",
		"Yes", "MayorPick",
		"No", "idlesuspects"],
	
	label, "susp3",
	set, {numForms:"-1"},
	cform, ["sus3", true,
		button, {name:"Suspect1", x:200, y:90, w:120, h:225, base:"Images/constablethumb.png", 
		link:[jump, "suspectconfirm1"], showText:false},
		button, {name:"Suspect2", x:325, y:90, w:120, h:225, base:"Images/mayorthumb.png", 
		link:[jump, "suspectconfirm2"], showText:false},	
		button, {name:"Suspect3", x:450, y:90, w:120, h:225, base:"Images/maidthumb.png", 
		link:[jump, "suspectconfirm3"], showText:false}],
	jump, "idlesuspects",
	label, "suspectconfirm3",
	text, {value:"Suspect\nMaid Leah. A rather grumpy woman who works for the Bungles. She doesn't seem to like her job very much.  I can't tell if she dim-witted or just very tolerant."},
	box, {show:false},
	jump, {suspectmode:false, label:"idlesuspects"},
	menu, ["Is this the suspect you wish you select?",
		"Yes", "MaidPick",
		"No", "idlesuspects"],

	label, "susp4",
	set, {numForms:"-1"},
	cform, ["sus4", true,
		button, {name:"Suspect1", x:200, y:90, w:120, h:225, base:"Images/constablethumb.png", 
		link:[jump, "suspectconfirm1"], showText:false},
		button, {name:"Suspect2", x:325, y:90, w:120, h:225, base:"Images/mayorthumb.png", 
		link:[jump, "suspectconfirm2"], showText:false},	
		button, {name:"Suspect3", x:450, y:90, w:120, h:225, base:"Images/maidthumb.png", 
		link:[jump, "suspectconfirm3"], showText:false},
		button, {name:"Suspect4", x:575, y:90, w:120, h:225, base:"Images/pickpocketthumb.png",
		link:[jump, "suspectconfirm4"], showText:false}],
	jump, "idlesuspects",
	label, "suspectconfirm4",
	text, {value:"Suspect\nPickpocket Dipper.  An energetic young boy who lives on the streets.  He seems like he could be a valuable source of information.  If only he didn't demand a bribe every time I wanted to ask questions."},
	box, {show:false},
	jump, {suspectmode:false, label:"idlesuspects"},
	menu, ["Is this the suspect you wish you select?",
		"Yes", "PickpocketPick",
		"No", "idlesuspects"],
];
